### ISSUE TITLE
解决易用性的问题

### ISSUE THREAD

**Issue by Backkom05** [OpenPuya/PY32F002B_Firmware#1]
对于业余爱好者，IAR显得太笨重，能否开发arduino类似平台，降低入门门槛？

**Comment by HalfSweet** [comment]
目前Puya官方原生支持的有 GCC/MDK/IAR 三大平台，arduino有第三方的社区支持 <https://github.com/py32duino> 以及 [py32-rs](https://github.com/py32-rs)
